### ISSUE TITLE
Missing SH script to get remote Postgres database

### ISSUE THREAD

**Issue by niksumeiko** [gousta/get-remote-pg-database#1]
:dancers:

**Comment by gousta** [comment]
Soon my friend. Be patient :)

**Comment by niksumeiko** [comment]
Why then you closed it? It's still relevant…

You can close it with a commit which is going to add the script itself. You know secret Github commit flags to close issues, right?

**Comment by gousta** [comment]
No, I haven't really used Github but only 3-4 months now. But we have Google, it knows these commands.

**Comment by niksumeiko** [comment]
Yes, Google definitely knows how to close issues automatically directly from Git commit messages.
